### ISSUE TITLE
Request second joystick emulation for mobile

### ISSUE THREAD

**Issue by dan-ewo** [jbaicoianu/janusweb#100]
Waving phone around is not useful in most use cases.

**Comment by jbaicoianu** [comment]
Added touchscreen turning in the last release - upcoming UI release will improve this even further with the addition of a "lock rotation" button to toggle the phone's gyro.

**Comment by dan-ewo** [comment]
Yep, that'll work! I suggest a triple tap on the joystick, joystick turns red, "X" in center to engage lock? Touch and slide again to unlock?
