### ISSUE TITLE
Entering into janusweb a second time while the Chrome is open, no movement, only look

### ISSUE THREAD

**Issue by dan-ewo** [jbaicoianu/janusweb#101]
If I fully shut down Chrome, and reopen it, I can operate Janusweb as normal. Then if I close the janusweb tab and open it again later, I have no movement past where I spawn. I can look around, however. This behavior continues until I fully shut down Chrome.

**Comment by jbaicoianu** [comment]
Strange, I've never seen this behavior.  Can you give me some details about your system (OS, chrome version, etc).

Is there a dialog sitting around anywhere on screen asking for permission to capture your mouse pointer, or did you already grant those permissions?

**Comment by jbaicoianu** [comment]
@dan-ewo If I recall correctly we traced this to an issue with Synergy, right?  Did you find a workaround?
