### ISSUE TITLE
Sound for some onclick objects is not working correctly

### ISSUE THREAD

**Issue by FireFoxxG** [jbaicoianu/janusweb#102]
The sound played when clicking on the big arrow pad(in the video/image sphere) is the same sound that should play with the playbutton and eye button. The sound technically is playing but is like 1000th as loud as it should be(barely audible on good earbuds).

http://demos.janusvr.com/firefox/youtube360/Vid_and_image_gallery/Gaze360Gallerytest.html

Click any image, click play button and woosh sound should play.

**Comment by jbaicoianu** [comment]
@FireFoxxG is this problem still happening?  I'm not sure the script for this room is working anymore.

**Comment by jbaicoianu** [comment]
I think this was fixed, it was related to the change from room.playSound() switching from asset id to js_id
