### ISSUE TITLE
implement thumb_id, and use in place of websurface on screenshots

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#104]

**Comment by jbaicoianu** [comment]
This is implemented in 1.5, seems to work great on the Lain page https://vesta.janusxr.org/spyduck/lains-bedroom-serial-experiments-lain

**Comment by jbaicoianu** [comment]
I guess this was a two-parter, thumb_id is implemented, and by default if you take a screenshot before activating the websurface, it'll show the thumb instead of a blank spot.  If you take a screenshot at some point after activating the websurface though, it'll still show the previous behavior.
