### ISSUE TITLE
Allow for pressing spacebar to toggle between Translate, Scale, and Rotate

### ISSUE THREAD

**Issue by HeadClot** [jbaicoianu/janusweb#107]
This would allow people to rapidly switch between translate, Scale, and Rotate.

It would also allow iteration to be faster.

**Comment by jbaicoianu** [comment]
Edit mode has been improved drastically for the upcoming version, in the new edit mode you can switch between translate/scale/rotate with tab, and either use the gizmo, input boxes, keyboard, or mousewheel to change the values.

![image](https://user-images.githubusercontent.com/251610/67080948-180f2e00-f14b-11e9-857b-1d809e5ac5f8.png)
