### ISSUE TITLE
room.objects[jsid].sync = true; only sends updates once.

### ISSUE THREAD

**Issue by scooterboo** [jbaicoianu/janusweb#110]
run https://nazrin.net/Test/bug1.html in both janusvr and janusweb at the same time. 
When you click the blocks in janusvr, they sync fine with the janusweb window.
But when you click the blocks in the janusweb window, they stay down in the janusvr window.

**Comment by jbaicoianu** [comment]
Fixed in #129 (thanks @Spyduck!) - will go out with 1.2
