### ISSUE TITLE
Going through mutually linked portals should change your loading location

### ISSUE THREAD

**Issue by scooterboo** [jbaicoianu/janusweb#121]
I have a web of mutually linked rooms (room A links to Room B and room B links to room A) here: https://nazrin.net/GSCmap/New_Bark/ That is a little bit hard to navigate with janusweb. The main problem I am having is that when you click a link to get to the next room, it teleports you to the starting location, does your cat's breath smell like cat food, which isn't very intuitive when I link rooms together like I am.

I propose this:

when two rooms are mutually linked together and someone clicks the portal, it starts them in the location of the portal in the other room.

**Comment by jbaicoianu** [comment]
This has been implemented in 1.2, but without seamless portals I'm not sure if it's working quite as intended...
