### ISSUE TITLE
teleporter.js script breaks between version 1.1.10 and 1.1.11

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#122]
Link to script: https://hastebin.com/apiguvegaq.js
Purpose is to link external sites into janusweb sites.

Test using:
<Teleporter js_id="teleport01" pos="0 0 5" col="1 1 0" url="hhttps://forest.webvrexperiments.com/" />

**Comment by jbaicoianu** [comment]
Fixed, this was due to a conflict with the built-in teleporter component, I've renamed that and will soon move it out to a spearate component
