### ISSUE TITLE
errors by build from source

### ISSUE THREAD

**Issue by BogusCurry** [jbaicoianu/janusweb#132]
Hello ;D
I have pull the actual source and have build from, becomes this error messages
https://paste.md-5.net/yixonevare.pl

I hope you can fix it ;D

Thats all under Linux Mint 18.3 local on my PC ;D

Greetings
Bogus

**Comment by jbaicoianu** [comment]
Looks like newer versions of nodejs must be more strict about reserved words like ```static```  - should be an easy fix

**Comment by jbaicoianu** [comment]
Oh - this actually was already fixed, it was actually an Elation Engine bug - I think you just need to make sure you've pulled down the latest version of the dependencies, and clear out the build environment.  From inside of the janusweb directory, try the following:
```
$ rm -rf elation node_modules
$ npm install --only=prod
```

(or you could maybe get away with just deleting the elation directory, and running npm update)

**Comment by BogusCurry** [comment]
I not now, what I make wrong, ok .. at first I have make delete the eletation modules with command and then install. If comes no errors, so run npm build script. But then comes errors .. Ok I have the output put in a pastebin, I hope you understand my steps and can see what I make wrong ;D 

Greetings

Bogus

**Comment by jbaicoianu** [comment]
I haven't been able to duplicate this issue, and by now we're several versions ahead of when this ticket was filed. If you're still experiencing this issue with a fresh checkout of the latest JanusWeb code (1.5.6) and updated node / npm, please feel free to reopen this issue.
