### ISSUE TITLE
lighting rotation issue

### ISSUE THREAD

**Issue by Aussie** [jbaicoianu/janusweb#140]
all the spotlights point towards (0,0,0) regardless of where they're positioned

native - [![Screenshot from Gyazo](https://gyazo.com/6be033d55c39c81d4ba6cf54baace53f/raw)](https://gyazo.com/6be033d55c39c81d4ba6cf54baace53f)

Vesta - [![Screenshot from Gyazo](https://gyazo.com/a936c534239f776bc71666ef54c82224/raw)](https://gyazo.com/a936c534239f776bc71666ef54c82224)
https://vesta.janusvr.com/aussie/art-gallery-shadows-and-lighting

**Comment by jbaicoianu** [comment]
Fixed, thanks!
