### ISSUE TITLE
Teleporter not working in latest version

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#142]
Made a test room for fixing teleporter.js, here's a version where it worked really great
https://web.janusvr.com/1.1.9/sites/https://vesta.janusvr.com/bepis/teleporter-test

I'm using the script hosted at https://www.metacade.com/traversal/teleporter.js, and it broke after janusweb version 1.1.10.

**Comment by jbaicoianu** [comment]
Duplicate of #122
