### ISSUE TITLE
JanusWeb doesn't show glTFs that have embedded mesh and images.

### ISSUE THREAD

**Issue by cfravel** [jbaicoianu/janusweb#150]
1. JanusWeb accepts drag and drop of gltf without embedding, and shows it properly
2. JanusWeb does NOT show gltfs with embedding.
3. JanusVR accepts drag and drop of glTF with embedded mesh and images, but doesn't show the material/texture
4. JanusVR does not show glTFs that don't have embedding.
5. Decentraland SDK works with either embedded or non-embedded glTFs

Example Scene:
http://www.fravel.net/webvr/JanusGltfTest/

My component palette for building this scene:
http://www.fravel.net/webvr/AetheriaContentLibrary/

In my palette:
Lady is gltf with separate .bin and image files in same inventory/palette server folder as the gltf
Gate is gltf with all the content embedded.

BTW, in the Khronos gltf exporter, export gltf not glb, and then check the two embedding checkboxes (buffer, images), but NOT the strip delimiters one

So:
JanusVR needs to show the textures for the gltf-embedded format, and really should display unembedded format gltf's also.

JanusWeb needs to show the gltf-embedded format

Also posted similar info to JanusVR github issues:
https://github.com/janusvr/janus/issues/5

**Comment by jbaicoianu** [comment]
This issue has already been fixed in my dev copy, I'll update and close this ticket once I've got that committed and pushed.

**Comment by jbaicoianu** [comment]
Fixed in 1.3 and pushed live
