### ISSUE TITLE
Joystick on mobile will break after tapping screen

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#154]
Noticed that tapping the screen outside of the joysticks will make the joysticks stop working.

Steps to reproduce:

1. Load a janusweb site
2. Look around on the screen OUTSIDE of the thumbpad buttons
3. The thumbpad buttons don't work anymore, will move the screen up and down revealing the address bar
4. It's a bit janky to re-enable the thumbpads again, gotta kinda double tap / hold press

It will break again after retapping the screen. Out of testing various methods for moving the camera, I think the best implementation is the Virtual Joysticks Camera implemented by babylon.js / cryptovoxels

https://www.youtube.com/watch?v=53Piiy71lB0

**Comment by jbaicoianu** [comment]
Seems to be working fine now
