### ISSUE TITLE
Websurface thumbnails are broken

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#155]
Been building rooms that have tons of websurfaces which has made it really critical to look into how to prevent everything from automatically loading. Noticed that the feature to add a thumbnail for a websurface is currently broken in janusweb, the test site is here:

https://vesta.janusvr.com/bepis/assetwebsurface-clone

Gotta add image_id to the line with the websurface_id.

**Comment by jbaicoianu** [comment]
Fixed in f38026733d00bf0eea09165f800969fc47223885
