### ISSUE TITLE
Texture bug with collada files in testing

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#157]
The cinema and Lut desert town are both collada models that display texture issues in dev version of janusweb. There was a pull request to three.js which fixed it like 8 months ago but wasn't accepted and the fix hasn't been applied when three.js got updated.

**Comment by jbaicoianu** [comment]
Fixed in dev, and the fix has been merged upstream now https://github.com/mrdoob/three.js/pull/15391
