### ISSUE TITLE
tex_linear stopped being applied

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#162]
Noticed that in this test room, tex_linear is not applying in janusweb but works fine in native:

https://vesta.janusvr.com/bepis/genesis-city-full

**Comment by jbaicoianu** [comment]
Fixed
![image](https://user-images.githubusercontent.com/251610/67086339-5b6e9a00-f155-11e9-9fc1-9b1b8c3ba2c6.png)
![image](https://user-images.githubusercontent.com/251610/67086387-76d9a500-f155-11e9-889f-5d886f8b3f35.png)
