### ISSUE TITLE
Drag and drop mp3 into janusweb doesn't work

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#163]
In the dev branch of janusweb drag and drop mp3 doesn't work, browser reads it as copy. Tested with 1.4 and drag n' drop mp3 works in there.

**Comment by jbaicoianu** [comment]
I added better MIME type detection for drag-dropped URLs, we should now automatically detect audio, video, image, or 3d models.

![image](https://user-images.githubusercontent.com/251610/67081089-5efd2380-f14b-11e9-87a0-69b7343e5ace.png)

If this was about local files though, I haven't tried that...
