### ISSUE TITLE
Default tonemapping settings are too bright in 1.4

### ISSUE THREAD

**Issue by jbaicoianu** [jbaicoianu/janusweb#169]
Consider dropping default tonemapping_exposure down into the .6 - .8 range

**Comment by madjin** [comment]
Rooms I found some bugs in

- https://vesta.janusvr.com/bepis/desert-voxels (model too bright despite lighting="true")
- https://vesta.janusvr.com/spyduck/cyberpunk-apartment-template (too bright)
- https://vesta.janusvr.com/bepis/coral-miku2 (transparent webm not working)
- https://vesta.janusvr.com/bepis/white-grid   (sbs3d transparent webm not working)

**Comment by jbaicoianu** [comment]
Fixed a lot of colorspace issues since this was filed, and these worlds look good now
