### ISSUE TITLE
flipy="true" doesn't work on lightmaps in 1.4.4

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#175]
test room: https://spyduck.net/janus/angkor_wat/flipy_test.html

This should look like https://spyduck.net/janus/angkor_wat/working_example.html when it's working. The second link has a manually flipped lightmap.

**Comment by jbaicoianu** [comment]
I think the confusion here is that in webgl, textures default to flipY true.  So if you want it to do the opposite, you actually set flipy="false" not true.
