### ISSUE TITLE
Weird graphics issue in 1.4.4 in Windows

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#176]
Not sure how to describe this, seems to affect any site in 1.4.4 and Windows (doesn't affect 1.3.2)

Video example: https://spyduck.net/files/sharex/C5CJ97N0LQRJPD3UO4ATU302.mp4

**Comment by jbaicoianu** [comment]
This appears to be fixed in 1.4.9 now, I can't reproduce it in Windows anymore.  If you still see the problem using https://web.janusvr.com/1.4.9/ reopen this issue and we'll see if we can narrow down what might be causing it.

**Comment by jbaicoianu** [comment]
This is back in 1.5.5+

**Comment by jbaicoianu** [comment]
Haven't seen this one in a while
