### ISSUE TITLE
transparent video issue

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#177]
Noticed that transparent alpha webm videos broke on Vesta, here's a couple test links:

https://vesta.janusvr.com/bepis/white-grid
https://vesta.janusvr.com/bepis/panel

**Comment by jbaicoianu** [comment]
😎
![image](https://user-images.githubusercontent.com/251610/67042903-b1076000-f0dd-11e9-8dc3-b8f1acd0698f.png)

**Comment by jbaicoianu** [comment]
Fixed, although sbs3d video is broken in this version.  I'll open a separate issue about that. https://github.com/jbaicoianu/elation-engine/commit/b04a064ec324685bc364459b2d718090bd743d99
