### ISSUE TITLE
Room editing support

### ISSUE THREAD

**Issue by jbaicoianu** [jbaicoianu/janusweb#20]
Admin mode could be used to provide room editing functionality.  Need to fix up some bugs to make it usable before enabling it.

**Comment by erictrose** [comment]
bumping for basic browser-to-janus/janus-to-browser editing functionality independent of the full JanusWeb application, maybe in https://github.com/jbaicoianu/JanusClientConnection or another repo if it doesn't logically fit in this repo.

**Comment by jbaicoianu** [comment]
Fixed, you can access admin mode by appending &admin=1 to any JanusWeb URL.  There are some bugs still, but basic functionality is complete.

**Comment by jbaicoianu** [comment]
There is also a reference for how to send raw room edits using JanusClientConnection here: https://github.com/jbaicoianu/JanusClientConnection/blob/master/tests/roomchange.html
