### ISSUE TITLE
Colors look washed out

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#208]
Here's the colors in version [1.5.0](https://web.janusxr.org/1.5.0/)

![](https://i.imgur.com/3Oq2ZqB.jpg)

Same room but in version [1.5.17/18](https://madjin.github.io/internet-archive-vr/indoor/)

![](https://i.imgur.com/kdyzI75.jpg)

Maybe something to do with gamma factor?

**Comment by jbaicoianu** [comment]
Found some cases where the diffuse texture wasn't using sRGB colorspace, fixed now
