### ISSUE TITLE
Performance issue with mesh colliders

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#209]
I noticed there's a large FPS difference between version 1.5.0 and version 1.5.18. Here's a test room:

https://web.janusxr.org/1.5.0/#janus.url=https%3A%2F%2Fgm3.github.io%2Fwebvrshop%2F
https://web.janusxr.org/1.5.18/#janus.url=https%3A%2F%2Fgm3.github.io%2Fwebvrshop%2F

Moving around in 1.5.0 I get 60 fps, however in 1.5.18 I'm unable to go past 30 fps.

**Comment by jbaicoianu** [comment]
The main issue here is the colliders, especially for the merchandise.  Most of this stuff is inside of display cases or on walls anyway, so it seems unnecessary for them to have colliders at all.  Recommend removing the colliders or building a simplified collider mesh.

![image](https://user-images.githubusercontent.com/251610/88767527-9bc06700-d12e-11ea-9a8f-ef5fa410e9bf.png)

That being said, there is an early-out check for mesh colliders which is currently disabled, I'll turn it back on once I get the rest of the mesh collider stuff working better

**Comment by jbaicoianu** [comment]
@madjin is there a new URL for this world?  Getting a 404 now, but I'd like to see how this runs with the new PhysX integration

**Comment by jbaicoianu** [comment]
Not sure about this world, but I've made massive improvements to mesh collider support in the past month, including doing preliminary sphere checks for each object and each triangle within the object, which has made mesh colliders significantly more reliable and performant
