### ISSUE TITLE
Gif support

### ISSUE THREAD

**Issue by jbaicoianu** [jbaicoianu/janusweb#21]
alu needs gifs

**Comment by shadoxx** [comment]
shadoxx also needs gifs

**Comment by jbaicoianu** [comment]
Almost working!  https://www.youtube.com/watch?v=6DcsQi8IaLg  Optimizing load performance now.

**Comment by jbaicoianu** [comment]
Let's call this one done.  There are some improvements that could be done, like using a worker to process the gif frames, but gifs have been supported for several releases now.
