### ISSUE TITLE
Depthmap asset loading as wrong type

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#212]
It keeps chopping out the extension. I changed the asset_id to even include the extension but my console says 404 and shows it without one.

Repo: https://github.com/janusxr-examples/360-viewer
Test URL: https://janusxr-examples.github.io/360-viewer/5/index.html

![](https://i.imgur.com/oaZ6y3X.jpg)

**Comment by madjin** [comment]
Here's a screenshot of it trying to load the depthmap as an image

![](https://i.imgur.com/0nTvO77.jpg)

**Comment by jbaicoianu** [comment]
Fixed in dev, this was because image loading was falling back on trying to use the image id as a relative URL, so the fallback for video was never triggering
