### ISSUE TITLE
Not initializing VR session in Firefox or Chrome.

### ISSUE THREAD

**Issue by dan-ewo** [jbaicoianu/janusweb#214]
Firefox 85.0 Chrome 88.0.4324.104

**Comment by jbaicoianu** [comment]
Can I get a bit more info about your setup - which headset are you trying to use?  Do the examples at https://webvr.info/samples/ work as expected?  Is the page you're loading hosted on https?

**Comment by dan-ewo** [comment]
Using Valve Index. webvr.info/samples is initializing VR. Vesta.janusxr.org is not. Exit VR and Exit AR are shown when starting page.
![image](https://user-images.githubusercontent.com/593923/106366460-d7600780-62f0-11eb-8092-5981715f7cac.png)

**Comment by madjin** [comment]
Some screenshots from Discord for same bug

Enabled WebXR in chrome:flags

![image](https://user-images.githubusercontent.com/32600939/106400788-81b15b00-63d5-11eb-84c8-3b9193de2fbe.png)

Console log

![image](https://user-images.githubusercontent.com/32600939/106400772-6fcfb800-63d5-11eb-9330-5456a53d5bda.png)

Eventually memory leak / BSOD

**Comment by jbaicoianu** [comment]
Seems related to this bug, Chrome pushed out some updates which require a gl context to be recreated when passed to a WebXR session, related to running WebXR on multi-GPU systems.  Looks like I'll need to make sure the WebGL context is marked as WebXR compatible before trying to initialize WebXR.

https://github.com/mrdoob/three.js/issues/20715

**Comment by jbaicoianu** [comment]
I did a quick and dirty patch to the live version to work around this problem by doing exactly what Toji said not to do, forcing `xrCompatible: true` at context creation time, which fixes it for me.  Give it a try and if it still doesn't work go ahead and reopen this issue.  We should inherit the proper solution next time we upgrade ThreeJS.
