### ISSUE TITLE
edit: unable to spawn primitives

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#227]
tried drag n dropping a cube into the scene, doesn't show up
brave win10

![image](https://user-images.githubusercontent.com/32600939/143731820-4332b84e-00aa-463b-93d6-f9e09e6fa2e2.png)

console output
![image](https://user-images.githubusercontent.com/32600939/143731847-f7c8d30c-59e7-4d1c-a969-bae5a1117bed.png)

test site: https://tiny-sun-5459.on.fleek.co/

**Comment by jbaicoianu** [comment]
Fixed in dev
