### ISSUE TITLE
Edit mode: inspector doesn't update new assets

### ISSUE THREAD

**Issue by madjin** [jbaicoianu/janusweb#229]
The code editor updates with new assets (dragged n dropped primitives from inventory into scene) but not the scene editor in inventory tab

![image](https://user-images.githubusercontent.com/32600939/143732060-647fd6ff-3bb0-4841-987d-2f79ac7cb55b.png)

**Comment by jbaicoianu** [comment]
Fixed, this was because the scene tree only shows objects with `persist="true"` set, and the editor wasn't setting that parameter for newly-spawned objects. The newly-updated editor does that, and I also set persist="true" for files that are drag-dropped from the local system
