### ISSUE TITLE
How can use Janusweb ?

### ISSUE THREAD

**Issue by BogusCurry** [jbaicoianu/janusweb#25]
Hello ;D 
I have clone the source to my server and have install node.js, but how I can start the webclient in my browser ?

Greetings
Bogus

**Comment by jbaicoianu** [comment]
Hi Bogus,
First step is to check out all the dependencies and build a release version.  This is covered in the wiki - https://github.com/jbaicoianu/janusweb/wiki - just two npm commands are necessary.

Once it is built, you just need to make the build/ directory available somewhere, this does not require node.js if you have an existing HTTP server running - just put the files somewhere web-accessible. 

If you're starting from scratch and don't have an existing webserver, you could use https://www.npmjs.com/package/http-server to serve the static files by running ```http-server build/```

**Comment by BogusCurry** [comment]
Hi ;D
thanks for the fast answer ;D

Greetings
Bogus

**Comment by jbaicoianu** [comment]
No problem, let me know how it works out for you.

**Comment by BogusCurry** [comment]
Hmm .. I have nginx installed and run fine, but when I make npm install in the folder janusweb, so comes this 
http://paste.md-5.net/valowoxitu.hs

I have run the command with sudo What make I wrong ?

**Comment by jbaicoianu** [comment]
Seems like some package might be missing from your build environment.  You might have to run "apt-get install build-dependencies" if you've never done this before (assuming Debian, based on your logs)

You should't need sudo to run this.

**Comment by BogusCurry** [comment]
I use Ubuntu 14.04 and can't install the package.

**Comment by jbaicoianu** [comment]
Sorry my bad - it's ```apt-get install build-essential```

**Comment by BogusCurry** [comment]
Ahh ok .. np ;D
When I will install this package, comes this
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version.
build-essential set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

I not know, but can maybe I have install a wrong version from node.js ?
See here
gyp ERR! node -v v0.10.25
gyp ERR! node-gyp -v v0.10.10
gyp ERR! not ok

**Comment by jbaicoianu** [comment]
Hmm.  If you already have build-essential maybe you also need ```libcairo2-dev``` and ```libfreetype6-dev```.  If those don't work, maybe check the node-canvas project page and see if they have any info on this, I seem to remember this being a common problem for others.

**Comment by BogusCurry** [comment]
Puhh .. Ok I have now 2 errors ? when I make npm install .. see here .. http://paste.md-5.net/pivugikofu.vbs
On the projekt-page of node-canvas has I found this https://github.com/Automattic/node-canvas/issues/788 But I now know, is that the same problem that I have and second is very difficult to understand, so englisch is not my motherlanguage.
I see in the messages that the script not found two node modules ?

**Comment by jbaicoianu** [comment]
Oh, looks like node-canvas still uses the legacy nodejs binary name.  Try ```apt-get install nodejs-legacy```

**Comment by BogusCurry** [comment]
Ok, the install runs now, when I make a build comes this http://paste.md-5.net/xikedoyaje.hs

I see is a very hard way, this software to use .. lol

**Comment by jbaicoianu** [comment]
Sorry you're having difficulties, but I think so far it's all been node-canvas's fault, and the fact that your system was missing some dependencies.

Now that you have those, I'd suggest retrying the build step from the beginning - it seems that something just didn't get set up right the first time through.

**Comment by BogusCurry** [comment]
yes, I will install over weekend janusweb local on my pc under linux ;D 

Have a nice day ;D

**Comment by jbaicoianu** [comment]
By the way there is another much simpler way to use JanusWeb which does not require you to install and build the source code.  You can simply add this to the same HTML file which has your ```<FireBoxRoom>``` code:

    <script src="https://janusweb.metacade.com/janusweb.js"></script>

This will automatically launch JanusWeb when the page is loaded.

**Comment by BogusCurry** [comment]
Thats great ;D Thanks for your wonderful support ;D

Have a very nice Day ;D

**Comment by BogusCurry** [comment]
Hello ;D
can you me give a example for a room with the FireBoxRoom ?

**Comment by jbaicoianu** [comment]
@BogusCurry take a look at http://janusvr.com/guide/building.html#http://janusvr.com/notes.html - this shows you how to create a FireBoxRoom, and has a few examples.  Just add the ```<script>``` tag fro above at the end of the file and you should be good to go.

**Comment by BogusCurry** [comment]
@jbaicoianu Here is my 3D Room with JanusWeb, but I see a white site .... see you more as I ?

**Comment by jbaicoianu** [comment]
Ahh, now you're hitting some fun bugs :)  

Two problems, one is my fault - I forgot one line above, you'll also need to add this additional line after the first script tag:

    <script>elation.janusweb.init()</script>

The second problem is that JanusVR's ```FireBoxRoom``` markup is XML, but since it's embedded inside of an HTML page the browser is doing some manipulation to try to turn it into "valid" HTML before JanusWeb can read it.  However, after the browser does that, the markup is no longer valid XML, so it can't be parsed.

The solution is to enclose your ```<FireBoxRoom>``` markup in an HTML comment, like this:

    

The JanusVR team is working on a v2.0 of their markup which will integrate better with HTML, but until they do this is an easy work-around.
