### ISSUE TITLE
videos don't play on android webvr build

### ISSUE THREAD

**Issue by alusion** [jbaicoianu/janusweb#27]
Tried playing a 360 video on latest android chromium apk, fails to even load. Here's the hash of the build in question:
https://ipfs.io/ipfs/QmczPrq7pyTNRU1DRq9aR9Sj8qbNUyoffJLxZUCmnTcHkr/

**Comment by jbaicoianu** [comment]
Chromium webvr builds are missing most video codecs, particularly mp4.  Nothing I can do about this until they start shipping official Chrome builds, unfortunately.

FF Nightly now supports the latest Webvr spec, maybe they work there?

**Comment by jbaicoianu** [comment]
Chrome Beta on Android now supports WebVR, but requires you to get an Origin Trial access token for your domain.  Marking as fixed, since there's not much we can do until this hits mainstream
