### ISSUE TITLE
TypeError: room.getObjectById is not a function

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#29]
TypeError: room.getObjectById is not a function
Test url: http://spyduck.net/index.html
Expected behavior: portals in picture frames will immediately move out of view until the pictures are clicked
Result: nothing happens, "TypeError: room.getObjectById is not a function" error repeatedly

**Comment by jbaicoianu** [comment]
Fixed

**Comment by jbaicoianu** [comment]
Note that there are a couple other bugs which prevent the scripted portal moving from working - #31 and  #32
