### ISSUE TITLE
Using different image_id's on the same AssetObject (on different Object lines) does not function as expected

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#30]
Test url: http://spyduck.net/index.html
Expected behavior: all instances of painting_sphere use different image_id's
Result: all painting_sphere objects have the same image (the first image_id assigned)

**Comment by jbaicoianu** [comment]
Probably related, Aussie reports that if you have two photospheres with different videos, clicking one of them starts both.

http://www.libertyvr.com/home/bakes/vivespace/aussievivespace.html

**Comment by jbaicoianu** [comment]
This has been fixed for a couple releases now
