### ISSUE TITLE
Can install janusweb under LinuxMint 18

### ISSUE THREAD

**Issue by BogusCurry** [jbaicoianu/janusweb#41]
Hello ;D
I have a problem to install janusweb local under linuxmint 18

this is my error messages ...
http://paste.md-5.net/welimaseyu.vbs

Can you check this ;D

Have a nice Day ;D
Bogus

**Comment by jbaicoianu** [comment]
This is a common problem with node-canvas, I believe the fix is to make sure you have libgif installed.  In Ubuntu/Debian, this is provided by the libgif-dev package.  I'm not too familiar with Mint, but I believe you should just need to run ```apt-get install libgif-dev```, then try again.

**Comment by jbaicoianu** [comment]
Found another workaround.  If you aren't going to be running the unit tests, there's no need to compile all the devDependencies.  I've updated the README with more detailed instructions, the important part is this:

```
npm install --only=production
```

Or if you have an older version of npm, the argument is different:
```
npm install --production
```
