### ISSUE TITLE
need tex_linear="false"

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#50]
Comparison of Native and Web in a room with tex_linear="false" on objects:

https://spyduck.net/files/personal/screenshots/sharex/1490476136_2017-03-25_17-08-55.png
https://spyduck.net/files/personal/screenshots/sharex/1490476195_2017-03-25_17-09-50.png

**Comment by jbaicoianu** [comment]
Fixed - apparently trying to use GL_NEAREST with anisotropic filtering causes it to silently fall back to GL_LINEAR.  Now we force anisotropy to 1 if the texture is set to use nearest filtering.
