### ISSUE TITLE
Can not install janusweb under Ubuntu 16.04 server

### ISSUE THREAD

**Issue by BogusCurry** [jbaicoianu/janusweb#52]
Hello ;D
I have a little problem with janusweb, I have npm and node-js install over ppa from ubuntu. I will install janusweb on a server, but I becomes by install this message in the log-file 
https://paste.md-5.net/kafitowoqa.md

My question, if the nod-js version to low for janusweb ? or is another problem ?

Greetings

Bogus

**Comment by jbaicoianu** [comment]
If you checked out the janusweb repo from github, then from inside of this directory you just need to run ```npm install --only=prod``` - no need to specify the "janusweb" argument.

**Comment by jbaicoianu** [comment]
Going to consider this resolved, feel free to reopen if the instructions don't work for you
