### ISSUE TITLE
add audio mute option

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#53]

**Comment by jbaicoianu** [comment]
There is a keybinding to mute the client, ```ctrl+m``` will toggle mute on and off.  The new splash screen will also have a way to mute before loading the experience too.  Is this what you mean or did you have some other ideas?

**Comment by Spyduck** [comment]
just a way to do it through javascript. I've got a script going between pages ot screenshot but sometimes audio blares out the speakers, and I'm running it without the UI up so I can't just mute it.

**Comment by jbaicoianu** [comment]
I added a "muted" parameter to the client in this commit https://github.com/jbaicoianu/janusweb/commit/416c7a21c077cc3d17a3d8ae78d33f93b2928bb2

eg:
```js
elation.janusweb.init({url: document.location.href, muted: true})
```

**Comment by jbaicoianu** [comment]
Will go out with 1.1.1
