### ISSUE TITLE
JanusWeb does not show Paragraph tag.

### ISSUE THREAD

**Issue by alusion** [jbaicoianu/janusweb#57]
The paragraph tag shows up as a blue box with no text on it inside JanusWeb.
see:  http://janusvr.com/guide/markuplanguage/index.html#paragraph
Site tested: https://kool.website/lab/retrip.html
screenshots: http://imgur.com/a/IngTK

**Comment by jbaicoianu** [comment]
Paragraph is now fully implemented in 1.1.1
