### ISSUE TITLE
Bugs with the F6 code editor

### ISSUE THREAD

**Issue by alusion** [jbaicoianu/janusweb#62]
1.  If I launch the code editor once, I cannot bring it back up again as the F6 key will keep hopping to URL address bar.
2. I cannot update and preview any live changes made within the code editor.
3. Arrow keys are still being tracked while I'm in the code editor. Everytime I move around the code or highlight with shift+arrow keys my head rotation is being pulled along with it. Hit down arrow to scroll through the code to see what I mean.

**Comment by jbaicoianu** [comment]
1 and 2 are fixed in my dev copy, will work on 3 before closing this

**Comment by jbaicoianu** [comment]
3 is now fixed too, in 1.1.1
