### ISSUE TITLE
MasterJS testing room doesnt work in janusweb

### ISSUE THREAD

**Issue by FireFoxxG** [jbaicoianu/janusweb#69]
janus native vs janus web

https://i.gyazo.com/01c3fa2e1ca541e7b276aece84c420b2.png
https://i.gyazo.com/63379caafa43333a4743dd6c92ff0215.png

and the test environment

http://demos.janusvr.com.s3.amazonaws.com/firefox/1_of_Everything/MasterJS.html

**Comment by jbaicoianu** [comment]
Master JS test doesn't seem to be up anymore, in the future we should probably start fresh with new tests for JanusWeb
