### ISSUE TITLE
360 video spheres not working correct

### ISSUE THREAD

**Issue by Aussie** [jbaicoianu/janusweb#72]
should be 2 spheres with on-click videos, only one appears, wrong size and no video

https://gyazo.com/61f9d4697735b8e3dc12796e1fef65f9

http://www.libertyvr.com/home/bakes/vivespace/aussievivespace.html

https://web.janusvr.com/1.1.1/#janus.url=http%3A%2F%2Fwww.libertyvr.com%2Fhome%2Fbakes%2Fvivespace%2Faussievivespace.html

**Comment by jbaicoianu** [comment]
I think this bug is probably fixed now, unfortunately it looks like libertyvr.com stopped working :(
