### ISSUE TITLE
changing player orientation with js isn't working in 1.1.1

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#75]
Test pages for comparison: "current" version: http://spyduck.net/preview_cam.html
1.1.1: http://paradox.spyduck.net/rooms/garbage/preview_cam_test.html

1.1.1 just sits there and spams this error:
Uncaught TypeError: 'set' on proxy: trap returned falsish for property '_x'

**Comment by jbaicoianu** [comment]
This was resolved in chat, turns out it was a problem with euler angles vs quaternions.  There is an underlying problem with the way I'm setting up the ES6 proxy objects for the scripting engine though, so I'll file a separate issue for that.
