### ISSUE TITLE
room edit syncing problem (image with nested paragraph)

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#77]
doesn't seem to come through on the janusweb side but works in native

`{"method":"user_moved","data":{"roomId":"b5e9751f8a345fc3e04c0296ced27020","userId":"VineyardBot_2000","position":{"up_dir":"0 1 0","room_edit":"<AssetImage id=^feb77e71c3f2461e54d860c4e2954eba^ src=^https://booru.vineshroom.net/_images/145c70b5d5cc0def742c62dfdc17f2c8/36345%20-%20farm%20game%3Acities_skylines%20scrungus%20streamer%3Avinny.png^ /><Image js_id=^feb77e71c3f2461e54d860c4e2954eba_1501704785.993684^ pos=^-4.526504792483604 1.6 4.7169263426558175^ fwd=^0.292188169790988 0 0.9563608489655946^ id=^feb77e71c3f2461e54d860c4e2954eba^ lighting=^false^><Paragraph back_col=^#000000^ back_alpha=^0.7^ text_col=^#ffffff^ scale=^2 2 2^ lighting=^false^ cull_face=^none^ pos=^0 -1 0^>By Moremetals</Paragraph></Image>","pos":"-4.234316622692616 0.1 5.673287191621412","dir":"-0.292188169790988 0 -0.9563608489655946","view_dir":"-0.292188169790988 0 -0.9563608489655946","anim_id":"idle","_userId":"VineyardBot_2000","_userList":[]}}}`

actual example of a packet being sent

**Comment by jbaicoianu** [comment]
Fixed in my dev copy, we weren't handling assets properly - now we are.  Will go out with the next patch release.

Thanks, including the packet info was very helpful for debugging this.
