### ISSUE TITLE
lighting is reversed between janusvr and janusweb

### ISSUE THREAD

**Issue by alusion** [jbaicoianu/janusweb#83]
Between scenes and avatars, either the web or native client seem to have lighting flipped. Visit metacade in native client and everything is dark and avatars that have lighting="false" in janusweb are dark as well.

**Comment by jbaicoianu** [comment]
I'm gonna call this issue resolved - lighting has gone through a lot of revisions since 2017, and the native client is no longer supported, so whatever the web client is doing is now the new baseline :sweat_smile:
