### ISSUE TITLE
chat window small but important fixes

### ISSUE THREAD

**Issue by karansher** [jbaicoianu/janusweb#89]
-the text field in chat should say "Click here to chat" instead of "Press T to talk". newbies are pressing T, it does not do anything and will never click in the field. also i dont think we have voip here yet, but as and when we do, it should be V for voice to be consistent with janus native. URGENT.

-somehow add info when janusweb get focus that WASD can be used to move around. mouse motion is discoverable by itself, WASD is not. i like the ESC to get focus back pop-up that comes from the browser itself. it would be nice to have something like that. if not we still need someway, maybe just a small infograhic above the janusWeb ui buttons. URGENT.

-remove the -ox on the chat window chrome, because they do nothing. the chat button toggles it. LESS URGENT.

**Comment by jbaicoianu** [comment]
The UI has changed a lot since this bug was open, closing
