### ISSUE TITLE
The alpha on an Object does not render properly.

### ISSUE THREAD

**Issue by scooterboo** [jbaicoianu/janusweb#91]
https://vesta.janusvr.com/nazrin/bug-testing-room-2
Should look like:
![image](https://user-images.githubusercontent.com/1877986/30560555-23e490ce-9c6d-11e7-89c0-7fb12ab3515e.png)
When alpha is supported

**Comment by jbaicoianu** [comment]
Added support for 4-component color vectors in dev copy, will go out with next release.  Spheres 7, 8, and 9 still have issues because they're set using the individual elements of the color vector rather than assigning a color vector, considering this separate issue because it also affects vectors
