### ISSUE TITLE
createObject doesn't work with rotation

### ISSUE THREAD

**Issue by KooIaIa** [jbaicoianu/janusweb#95]
Load this script in your room and it will spawn 3 default cubes:

https://pastebin.com/Ag7yYASk

Bad - Red Cube uses createObject with rotation and doesn't rotate

Good - Green Cube is rotated 3 seconds after createObject with the same rotation and correctly rotates

Bad - Blue cube is rotated right after createObject with the same rotation as Green and does not rotate

**Comment by jbaicoianu** [comment]
This was fixed with the last release, please try https://vesta.janusvr.com/bai/bug-test-room-95 and confirm.  If the issue persists, feel free to reopen!
