### ISSUE TITLE
light color doesn't change when setting light.col

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#96]
test room: https://web.janusvr.com/sites/https://wired.spyduck.net/rooms/cyberia/index2.php

**Comment by jbaicoianu** [comment]
@Spyduck is there a version of this room which shows the original bug?  looks like this one has the ambient workaround you mentioned

**Comment by Spyduck** [comment]
that URL showcases it but to make it more obvious I've commented out the ambient portion

**Comment by Spyduck** [comment]
messed around a little more, realized I can manually update the light color with this code:
room.objects["light_main1"].col = getBeamcolor(color%6+7);
room.objects["light_main1"].updateLight();
getBeamcolor is obviously one of my functions, seems like janusweb just needs to do the updateLight() function when col is set

**Comment by jbaicoianu** [comment]
Fixed in dev, will go out with the next release
