### ISSUE TITLE
sounds give errors about gain and then break the rest of the page

### ISSUE THREAD

**Issue by Spyduck** [jbaicoianu/janusweb#97]
Test url: http://wired.spyduck.net/rooms/cyberia/index.php

gives tons of errors about the gain attribute then a lot of the objects never even load. Commenting out the Sound lines under Room fixes it

**Comment by jbaicoianu** [comment]
Looks like the page is failing to parse because ```loop="true"``` is specified twice in this line:

```<Sound id="music_1" js_id="js_music_1" loop="true" visible="false" play_once="false" loop="true" pos="-0.2 5 0.2" gain="0.2" dist="0.5" />```

Browser XML parsers throw an error on this XML, and stop parsing all objects after this point, so then the js update function is trying to access an object which was never created.

See #48 for more details
