### ISSUE TITLE
js object rotation (xdir,ydir,zdir) settings not quite working

### ISSUE THREAD

**Issue by karansher** [jbaicoianu/janusweb#98]
check out
https://web.janusvr.com/sites/http/demos.janusvr.com/karan/poolhall2/Parallelogram.html

click the white ball after the room loads. you will see the balls move around but they dont rotate.
if you look here 
http://demos.janusvr.com/karan/poolhall2/maya2JanusAnim.js

every frame update there is a call that makes a bunch of pos, xdir, ydir etc. settings. (see below)
i remember you saying something about things not getting dirty unless assigned in one shot using Vector. easy for me to change but curious as to why pos.x assignment is working and not xdir.x then?

room.objects[objarr[i]].pos.x=anim_data[globalFrame*15*objcnt+15*i];
	room.objects[objarr[i]].pos.y=anim_data[globalFrame*15*objcnt+15*i+1];
	room.objects[objarr[i]].pos.z=anim_data[globalFrame*15*objcnt+15*i+2];
	room.objects[objarr[i]].xdir.x=anim_data[globalFrame*15*objcnt+15*i+3];
	room.objects[objarr[i]].xdir.y=anim_data[globalFrame*15*objcnt+15*i+4];
	room.objects[objarr[i]].xdir.z=anim_data[globalFrame*15*objcnt+15*i+5];
	room.objects[objarr[i]].ydir.x=anim_data[globalFrame*15*objcnt+15*i+6];
	room.objects[objarr[i]].ydir.y=anim_data[globalFrame*15*objcnt+15*i+7];
	room.objects[objarr[i]].ydir.z=anim_data[globalFrame*15*objcnt+15*i+8];
	room.objects[objarr[i]].zdir.x=anim_data[globalFrame*15*objcnt+15*i+9];
	room.objects[objarr[i]].zdir.y=anim_data[globalFrame*15*objcnt+15*i+10];
	room.objects[objarr[i]].zdir.z=anim_data[globalFrame*15*objcnt+15*i+11];
	room.objects[objarr[i]].scale.x=anim_data[globalFrame*15*objcnt+15*i+12];
	room.objects[objarr[i]].scale.y=anim_data[globalFrame*15*objcnt+15*i+13];
	room.objects[objarr[i]].scale.z=anim_data[globalFrame*15*objcnt+15*i+14];

**Comment by jbaicoianu** [comment]
The reason position works is because the position vector is bound directly to the position vector used by the underlying engine.  xdir/ydir/zdir are "synthetic" properties, the actual rotation is represented under the hood by a quaternion, and we only update the quaternion from xdir/ydir/zdir when one of them changes.  This way, we don't clobber changes to orientation from physics - only when a script changes those values.

**Comment by karansher** [comment]
Got it. How about scale?

I’ll change the xdir etc. to use Vector.

Also if we use inbuilt primitives cube, sphere and plane, does jweb pass them as such to underlying physics. That could be quite powerful.

-karan

**Comment by jbaicoianu** [comment]
Yes, scale is mapped directly to the underlying vector object, so that should be fine too.

Yes, we do remap primitives to physics primitives, so if you specify a collision_id of sphere, cube, cylinder, or plane we'll automatically use the optimized primitive colliders

**Comment by jbaicoianu** [comment]
Also important to note that we use separate systems for collision detection vs raycasting (eg, mouse/gaze selection). Raycasting is done against the full geometry, whereas collision detection uses code specific to varios primitive interactions (sphere-sphere, sphere-cylinder, sphere-cube, cube-cube, etc)

**Comment by jbaicoianu** [comment]
This is fixed now, the pool cue faces the right direction and the balls rotate as expected

**Comment by karansher** [comment]
It has been doing so for a while J.

https://vesta.janusvr.com/karan/pool-table

-k
