### ISSUE TITLE
Sound persists through next room

### ISSUE THREAD

**Issue by dan-ewo** [jbaicoianu/janusweb#99]
https://vesta.janusvr.com/gunpigew/gunpigew-landing go here, click on portal, engine sound carries on despite what room you are in.

**Comment by jbaicoianu** [comment]
Think I have a fix for this in my dev copy, but I can't test on the linked room, seems like there's an XML error:

```



<Object id="pipe" js_id="g6" pos="-304.450714 -0.003854 4.54465" xdir="0.121036 0.004367 0.992638" ydir="-0.003922 0.999985 -0.003922" zdir="-0.99264 -0.003418 0.121052" collision_id="pipe" rotate_axis="0 0.5 0" rotate_deg_per_sec="30" >
    <Object id="AC-130" js_id="g7" pos="304 13 1" xdir="0.965928 0.258813 0.000002" ydir="-0.258813 0.965928 -0" zdir="-0.000002 -0.000001 1" >
          <Sound id="props" pos="0 0 0" dist="1.0" gain="2" loop="true" />
    </Object>
```
Note the missing </Object> to close out the <Object id="pipe">
 


```

**Comment by jbaicoianu** [comment]
This was fixed a couple releases ago, if the issue persists please feel free to reopen with whatever additional info you may have.
